### ISSUE TITLE
Missing path issue with using libraries

### ISSUE THREAD

**Issue by shivams** [nrobinson2000/po-util#46]
I often encounter the following issue with using libraries using `po-util`. 

In some libraries, certain files within the library include other files of that library assuming that the path is known by the compiler. E.g. many of the libraries come with `examples` folders which include the parent library files assuming a certain path structure. However, when doing `po <DEVICE> build`, the build fails because of path issues saying that no such file exists. What I do currently is that I simply remove those example folders, but that's a temporary solution.

How do we change the include path of the compiler when using `po-util` in such cases? Or, is there some other solution?

**Comment by nrobinson2000** [comment]
@shivams I have discontinued po-util. All future development efforts will be spent on neopo, a much more portable utility built with python. https://github.com/nrobinson2000/neopo

With neopo, the Libraries 2.0 structure is fully supported since neopo relies on the same dependencies as Particle Workbench. The issue you are experiencing should not be present in neopo.

**Comment by shivams** [comment]
Wow... Thank you @nrobinson2000 for the new project and it even supports Windows! That would be very convenient :+1:
