### ISSUE TITLE
po-util should only install missing components if possible.

### ISSUE THREAD

**Issue by mrmowgli** [nrobinson2000/po-util#5]
I'm realizing there are some parts of the script which may need some tweaking, specifically the following cases:

**Installation**
- User has multiple ARM-gcc installs for different platforms
- User has a more recent version of Node.js around
- User already has brew installed (OSX)

**Updating**
- Updating the particle-cli util
- updating firmware sources
- supporting multiple branches or checkout latest by default

**Misc** 
- User has a combination of Photon and Electron devices to support

**Possible tasks:**
- [x]  For ARM-gcc installs, check versions and see if it's necessary to install
- [x]   For Ubuntu builds (and possibly OSX) download gcc-arm-abi-none and run from ~/bin
- [x]  Have po-util set bin paths on run, and (possibly) export paths to put compiler first in path
- [x]  Check Node Versions and only install if neccesary
- [x]  Check for Brew existence 
- [x]  Set the default firmware branch to latest

**Comment by mrmowgli** [comment]
See the [build instructions for Ubuntu 14.04](https://community.particle.io/t/how-to-install-the-spark-toolchain-in-ubuntu-14-04/4139/7) for some of the changes I am proposing.

I know that I am currently using several versions of the gcc-arm-abi-none compilers, and apparently the firmware will only run on that specific version for some reason.

**Comment by nrobinson2000** [comment]
### Installation

> User has multiple ARM-gcc installs for different platforms
- This would be a rare case I think.  However we could try to isolate `gcc-arm-embedded` in its own directory like you mentioned above.

> User has a more recent version of Node.js around
> User already has brew installed (OSX)
- The reason for using an older, but stable verion of Node.js is because particle-cli can not be installed with the most recent version of Node.js because of the `serialport` package not having support for the release yet.
- The Homebrew installer script already checks if the user has Homebrew.  If they do, it skips directly to installing the packages.

### Updating

> Updating the particle-cli util
> updating firmware sources
- I have added this to the `update` part of po-util.

> supporting multiple branches or checkout latest by default
- Latest has been the default for a while.  I have made it so in the settings file you can now change your branch.

### Misc

> User has a combination of Photon and Electron devices to support
- Using `po photon` and `po electron` allows you to compile for different devices.  It is sometimes necessary to run `po DEVICE clean`

### Possible tasks

> Check Node Versions and only install if necessary
- This would take a bit of research.  We would have to see what would be the best stable version to install that would still work with the `particle-cli` dependencies.

**Comment by nrobinson2000** [comment]
Po-util now always installs the latest version of Node.js unless it is already installed.  I have added all of the features you specified, and will be closing this issue.
